<?xml version="1.0"?>
<package format="3">
  <name>pickcell_isaac_sim</name>
  <version>0.1.0</version>
  <description>Isaac Sim scene and ROS 2 bridge configuration for PickCell.</description>
  <maintainer email="mahdi@example.com">Mahdi</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
