#!/usr/bin/env python3
# flake8: noqa: E402
"""Import PickCell, render an overhead RGB-D camera, and publish ROS 2 data."""

import argparse
import json
from pathlib import Path
import random
import shutil
import traceback


def parse_arguments():
    """Parse arguments before starting Isaac Sim."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--urdf", required=True)
    parser.add_argument("--usd-dir", required=True)
    parser.add_argument("--pickcell-description", required=True)
    parser.add_argument("--kuka-description", required=True)
    parser.add_argument("--headless", action="store_true")
    parser.add_argument("--test-steps", type=int, default=0)
    parser.add_argument("--dataset-samples", type=int, default=0)
    parser.add_argument("--dataset-output", default="datasets/bags_synthetic")
    parser.add_argument("--dataset-seed", type=int, default=42)
    parser.add_argument("--min-bags", type=int, default=1)
    parser.add_argument("--max-bags", type=int, default=9)
    return parser.parse_known_args()


args, _unknown = parse_arguments()

from isaacsim import SimulationApp


simulation_app = SimulationApp({
    "renderer": "RayTracedLighting",
    "headless": args.headless,
})

import isaacsim.core.experimental.utils.app as app_utils
import isaacsim.core.experimental.utils.stage as stage_utils
import isaacsim.core.experimental.utils.transform as transform_utils
import numpy as np
import omni
import omni.graph.core as og
import omni.replicator.core as rep
import omni.syntheticdata._syntheticdata as sd
from PIL import Image
from isaacsim.asset.importer.urdf.impl import URDFImporter, URDFImporterConfig
from isaacsim.core.simulation_manager import SimulationManager
from isaacsim.sensors.camera import Camera
from isaacsim.core.experimental.utils.semantics import add_labels
from pxr import Gf, UsdGeom, UsdLux


FRAME_ID = "overhead_depth_camera_optical_frame"
NAMESPACE = "pickcell"
DEPTH_TOPIC = "sensors/overhead_depth/depth/image_raw"
RGB_TOPIC = "sensors/overhead_depth/color/image_raw"
INFO_TOPIC = "sensors/overhead_depth/camera_info"
POINTS_TOPIC = "sensors/overhead_depth/points"
CAMERA_PATH = "/World/overhead_depth_camera"
SIMULATION_RATE_HZ = 60
CAMERA_RATE_HZ = 15


def write_pointcloud_ply(
    path: Path,
    points: np.ndarray,
    colors: np.ndarray,
    normals: np.ndarray,
    semantic_ids: np.ndarray,
    instance_ids: np.ndarray,
) -> None:
    """Write an annotated point cloud in standard binary PLY format."""
    points = np.asarray(points).reshape(-1, 3).astype(np.float32)
    colors = np.asarray(colors).reshape(len(points), -1)[:, :3]
    normals = np.asarray(normals).reshape(len(points), -1)[:, :3]
    semantic_ids = np.asarray(semantic_ids).reshape(-1)
    instance_ids = np.asarray(instance_ids).reshape(-1)
    if len(semantic_ids) != len(points) or len(instance_ids) != len(points):
        raise ValueError("Point-cloud annotation arrays have different sizes")

    if np.issubdtype(colors.dtype, np.floating):
        color_scale = 255.0 if colors.max(initial=0.0) <= 1.0 else 1.0
        colors = np.rint(colors * color_scale)
    colors = np.clip(colors, 0, 255).astype(np.uint8)
    vertices = np.empty(len(points), dtype=[
        ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
        ("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4"),
        ("red", "u1"), ("green", "u1"), ("blue", "u1"),
        ("semantic_id", "<u4"), ("instance_id", "<u4"),
    ])
    for axis, column in zip(("x", "y", "z"), points.T):
        vertices[axis] = column
    for axis, column in zip(("nx", "ny", "nz"), normals.T):
        vertices[axis] = column
    for channel, column in zip(("red", "green", "blue"), colors.T):
        vertices[channel] = column
    vertices["semantic_id"] = semantic_ids.astype(np.uint32)
    vertices["instance_id"] = instance_ids.astype(np.uint32)

    header = "\n".join([
        "ply", "format binary_little_endian 1.0",
        "comment Generated by PickCell",
        f"element vertex {len(vertices)}",
        "property float x", "property float y", "property float z",
        "property float nx", "property float ny", "property float nz",
        "property uchar red", "property uchar green", "property uchar blue",
        "property uint semantic_id", "property uint instance_id",
        "end_header", "",
    ]).encode("ascii")
    with path.open("wb") as stream:
        stream.write(header)
        vertices.tofile(stream)


def convert_replicator_output(
    temporary: Path, output: Path, scenes: list[dict]
) -> None:
    """Convert synchronized Replicator frames into atomic scene folders."""
    for index, scene in enumerate(scenes):
        frame = f"{index:04d}"
        scene_directory = output / f"scene_{index:06d}"
        staging_directory = output / f".scene_{index:06d}.tmp"
        if scene_directory.exists() or staging_directory.exists():
            raise FileExistsError(
                f"Refusing to overwrite scene output for frame {frame}"
            )

        raw_instance_path = (
            temporary / f"instance_id_segmentation_{frame}.png"
        )
        raw_mapping_path = (
            temporary / f"instance_id_segmentation_mapping_{frame}.json"
        )
        raw_instance = np.asarray(Image.open(raw_instance_path))
        raw_mapping = json.loads(raw_mapping_path.read_text(encoding="utf-8"))
        expected_paths = {
            str(bag["name"]): str(bag["prim_path"])
            for bag in scene.get("bags", [])
        }
        bag_instances = []
        for raw_id, labels in raw_mapping.items():
            label_text = json.dumps(labels, sort_keys=True)
            matches = [
                name for name in expected_paths if name in label_text
            ]
            if len(matches) == 1:
                bag_instances.append(
                    (int(raw_id), expected_paths[matches[0]])
                )
        bag_instances.sort(key=lambda item: item[1])
        visible_sub_ids = [
            (raw_id, prim_path) for raw_id, prim_path in bag_instances
            if np.any(raw_instance == raw_id)
        ]
        grouped_bags = {}
        for raw_id, prim_path in visible_sub_ids:
            bag_name = next(
                part for part in Path(prim_path).parts
                if part.startswith("chemical_bag_")
            )
            group = grouped_bags.setdefault(
                bag_name, {"path": prim_path, "raw_ids": []}
            )
            group["raw_ids"].append(raw_id)
        visible_bags = [
            (tuple(grouped_bags[name]["raw_ids"]),
             str(grouped_bags[name]["path"]))
            for name in sorted(grouped_bags)
        ]
        expected_bag_names = set(expected_paths)
        mapped_bag_names = {
            part
            for _, prim_path in visible_bags
            for part in Path(prim_path).parts
            if part.startswith("chemical_bag_")
        }
        if not visible_bags or not mapped_bag_names.issubset(
            expected_bag_names
        ):
            image_ids = np.unique(raw_instance).tolist()
            mapped_bag_ids = [raw_id for raw_id, _ in bag_instances]
            raise RuntimeError(
                f"Frame {frame} has desynchronized instance annotations: "
                f"image IDs {image_ids}, mapped bag IDs {mapped_bag_ids}, "
                f"expected bags {sorted(expected_bag_names)}, mapped bags "
                f"{sorted(mapped_bag_names)}"
            )

        staging_directory.mkdir()
        try:
            _convert_replicator_frame(
                temporary, staging_directory, frame, scene,
                raw_instance, visible_bags,
            )
            staging_directory.rename(scene_directory)
        except BaseException:
            shutil.rmtree(staging_directory)
            raise

    shutil.rmtree(temporary)


def _convert_replicator_frame(
    temporary: Path,
    scene_directory: Path,
    frame: str,
    scene: dict,
    raw_instance: np.ndarray,
    visible_bags: list[tuple[tuple[int, ...], str]],
) -> None:
    """Convert one already-validated frame inside a staging directory."""
    shutil.copy2(temporary / f"rgb_{frame}.png", scene_directory / "color.png")
    depth = np.load(temporary / f"distance_to_image_plane_{frame}.npy")
    valid_depth = np.isfinite(depth) & (depth > 0.0)
    depth_mm = np.zeros(depth.shape, dtype=np.uint16)
    depth_mm[valid_depth] = np.clip(
        np.rint(depth[valid_depth] * 1000.0), 1, 65535
    ).astype(np.uint16)
    Image.fromarray(depth_mm).save(scene_directory / "depth.png")

    instance = np.zeros(raw_instance.shape, dtype=np.uint16)
    instance_mapping = {"0": "BACKGROUND"}
    semantics = {"0": {"class": "BACKGROUND"}}
    for instance_id, (raw_ids, prim_path) in enumerate(visible_bags, start=1):
        instance[np.isin(raw_instance, raw_ids)] = instance_id
        instance_mapping[str(instance_id)] = prim_path
        semantics[str(instance_id)] = {"class": "bag"}
    Image.fromarray(instance).save(scene_directory / "instance.png")
    (scene_directory / "instance_mapping.json").write_text(
        json.dumps(instance_mapping, indent=2) + "\n", encoding="utf-8"
    )
    (scene_directory / "semantics.json").write_text(
        json.dumps(semantics, indent=2) + "\n", encoding="utf-8"
    )
    camera_source = temporary / f"camera_params_{frame}.json"
    shutil.copy2(camera_source, scene_directory / "camera.json")
    rgb = np.asarray(Image.open(temporary / f"rgb_{frame}.png"))[:, :, :3]
    points, colors, normals, semantic_ids, instance_ids = (
        _pointcloud_from_images(
            depth, rgb, instance,
            json.loads(camera_source.read_text(encoding="utf-8")),
        )
    )
    write_pointcloud_ply(
        scene_directory / "pointcloud.ply",
        points, colors, normals, semantic_ids, instance_ids,
    )
    (scene_directory / "scene.json").write_text(
        json.dumps({
            **scene,
            "depth_encoding": "16UC1",
            "depth_unit": "millimetres",
            "pointcloud_unit": "metres",
            "pointcloud_frame": "opencv_optical",
        }, indent=2) + "\n",
        encoding="utf-8",
    )


def _pointcloud_from_images(
    depth: np.ndarray,
    rgb: np.ndarray,
    instance: np.ndarray,
    camera: dict,
) -> tuple[np.ndarray, ...]:
    """Back-project synchronized images into an optical-frame point cloud."""
    height, width = depth.shape
    projection = np.asarray(camera["cameraProjection"], dtype=np.float64)
    if projection.shape != (16,):
        raise ValueError("cameraProjection must contain 16 values")
    fx = abs(float(projection[0])) * width / 2.0
    fy = abs(float(projection[5])) * height / 2.0
    if fx <= 0.0 or fy <= 0.0:
        raise ValueError("camera projection has invalid focal lengths")
    rows, columns = np.indices(depth.shape, dtype=np.float32)
    z = depth.astype(np.float32, copy=False)
    valid = np.isfinite(z) & (z > 0.0)
    finite_z = np.where(valid, z, 0.0)
    xyz = np.stack((
        (columns - (width - 1) / 2.0) * finite_z / fx,
        (rows - (height - 1) / 2.0) * finite_z / fy,
        finite_z,
    ), axis=-1)

    derivative_u = np.gradient(xyz, axis=1)
    derivative_v = np.gradient(xyz, axis=0)
    normals = np.cross(derivative_u, derivative_v)
    lengths = np.linalg.norm(normals, axis=2)
    normal_valid = valid & np.isfinite(lengths) & (lengths > 1e-12)
    normals[normal_valid] /= lengths[normal_valid][:, None]
    normals[~normal_valid] = (0.0, 0.0, -1.0)

    return (
        xyz[valid].astype(np.float32),
        rgb[valid].astype(np.uint8),
        normals[valid].astype(np.float32),
        (instance[valid] > 0).astype(np.uint32),
        instance[valid].astype(np.uint32),
    )


def _write_annotator_frame(
    temporary: Path, frame: str, annotators: dict
) -> None:
    """Persist one synchronous direct-annotator snapshot for conversion."""
    rgb = np.asarray(annotators["rgb"].get_data())[:, :, :3]
    depth = np.asarray(annotators["depth"].get_data())
    instance_payload = annotators["instance"].get_data()
    raw_instance = np.asarray(instance_payload["data"])
    if raw_instance.max(initial=0) > np.iinfo(np.uint16).max:
        raise ValueError("renderer instance IDs exceed uint16 PNG capacity")
    raw_mapping = instance_payload["info"]["idToLabels"]
    camera_payload = annotators["camera"].get_data()
    camera_document = {
        key: value.tolist() if isinstance(value, np.ndarray) else value
        for key, value in camera_payload.items()
    }

    Image.fromarray(rgb.astype(np.uint8)).save(temporary / f"rgb_{frame}.png")
    np.save(temporary / f"distance_to_image_plane_{frame}.npy", depth)
    Image.fromarray(raw_instance.astype(np.uint16)).save(
        temporary / f"instance_id_segmentation_{frame}.png"
    )
    (temporary / f"instance_id_segmentation_mapping_{frame}.json").write_text(
        json.dumps({str(key): value for key, value in raw_mapping.items()}),
        encoding="utf-8",
    )
    (temporary / f"camera_params_{frame}.json").write_text(
        json.dumps(camera_document), encoding="utf-8"
    )


def select_dataset_output(requested: Path) -> Path:
    """Return an empty output directory without overwriting an earlier run."""
    requested = requested.expanduser().resolve()
    if not requested.exists():
        requested.mkdir(parents=True)
        return requested
    if not any(requested.iterdir()):
        return requested

    for run_index in range(1, 10000):
        candidate = requested.with_name(f"{requested.name}_{run_index:03d}")
        try:
            candidate.mkdir(parents=True, exist_ok=False)
        except FileExistsError:
            continue
        print(
            f"Dataset output is not empty; preserving it and using {candidate}",
            flush=True,
        )
        return candidate
    raise RuntimeError(f"Could not allocate a new dataset directory near {requested}")


def import_robot() -> str:
    """Convert the expanded workspace URDF to a USD stage."""
    config = URDFImporterConfig()
    config.urdf_path = str(Path(args.urdf).resolve())
    config.usd_path = str(Path(args.usd_dir).resolve())
    config.fix_base = True
    config.joint_target_type = "position"
    config.ros_package_paths = [
        {
            "name": "pickcell_description",
            "path": str(Path(args.pickcell_description).resolve()),
        },
        {
            "name": "kuka_quantec_support",
            "path": str(Path(args.kuka_description).resolve()),
        },
    ]
    output = URDFImporter(config).import_urdf()
    if not output:
        raise RuntimeError("Isaac Sim failed to import the PickCell URDF")
    return output


def create_clock_graph() -> None:
    """Publish Isaac simulation time on the standard /clock topic."""
    keys = og.Controller.Keys
    og.Controller.edit(
        {"graph_path": "/PickCellClock", "evaluator_name": "execution"},
        {
            keys.CREATE_NODES: [
                ("OnPlaybackTick", "omni.graph.action.OnPlaybackTick"),
                ("ReadSimTime", "isaacsim.core.nodes.IsaacReadSimulationTime"),
                ("PublishClock", "isaacsim.ros2.bridge.ROS2PublishClock"),
            ],
            keys.CONNECT: [
                ("OnPlaybackTick.outputs:tick", "PublishClock.inputs:execIn"),
                ("ReadSimTime.outputs:simulationTime", "PublishClock.inputs:timeStamp"),
            ],
            keys.SET_VALUES: [
                ("PublishClock.inputs:topicName", "/clock"),
            ],
        },
    )


def create_environment_light() -> None:
    """Add neutral illumination so the RTX RGB sensor observes the scene."""
    stage = stage_utils.get_current_stage()
    dome_light = UsdLux.DomeLight.Define(stage, "/World/environment_light")
    dome_light.CreateIntensityAttr(1000.0)


def find_bag_prims():
    """Return imported bag link prims in stable numeric order."""
    stage = stage_utils.get_current_stage()
    bags = [
        prim for prim in stage.Traverse()
        if prim.GetName().startswith("chemical_bag_")
        and prim.GetName()[-2:].isdigit()
    ]
    return sorted(bags, key=lambda prim: prim.GetName())


def hide_robot_for_dataset() -> None:
    """Hide KUKA geometry so it cannot occlude dataset observations."""
    robot_link_names = {
        "base_link",
        "link_1",
        "link_2",
        "link_3",
        "link_4",
        "link_5",
        "link_6",
    }
    hidden_links = []
    for prim in stage_utils.get_current_stage().Traverse():
        if prim.GetName() in robot_link_names:
            UsdGeom.Imageable(prim).MakeInvisible()
            hidden_links.append(prim.GetName())
    missing_links = robot_link_names.difference(hidden_links)
    if missing_links:
        raise RuntimeError(
            "Could not hide all robot links for dataset generation: "
            f"{sorted(missing_links)}"
        )


def set_bag_pose(prim, xyz, yaw_degrees: float) -> None:
    """Replace a bag link's local transform for synthetic rendering."""
    matrix = Gf.Matrix4d(1.0)
    matrix.SetRotate(Gf.Rotation(Gf.Vec3d(0.0, 0.0, 1.0), yaw_degrees))
    matrix.SetTranslateOnly(Gf.Vec3d(*xyz))
    UsdGeom.Xformable(prim).MakeMatrixXform().Set(matrix)


def randomize_bags(bag_prims, bag_count: int, rng: random.Random) -> list[dict]:
    """Create a stable bottom-up pallet stack with randomized pose jitter."""
    scene_bags = []
    for index, prim in enumerate(bag_prims):
        imageable = UsdGeom.Imageable(prim)
        if index >= bag_count:
            # RTX semantic visibility can lag USD visibility changes across
            # captures. Keep the prim visible and park it well outside the
            # camera volume so RGB, depth, and semantics share one pose-based
            # update path.
            imageable.MakeVisible()
            set_bag_pose(prim, (0.0, 0.0, -100.0 - index), 0.0)
            continue

        imageable.MakeVisible()
        layer = index // 2
        in_layer = index % 2
        if index == 8:
            x = rng.uniform(-0.04, 0.04)
            y = rng.uniform(-0.06, 0.06)
        else:
            x = rng.uniform(-0.055, 0.055)
            y_side = -1.0 if in_layer == 0 else 1.0
            y = y_side * rng.uniform(0.205, 0.265)
        z = 0.155 + 0.165 * layer + rng.uniform(-0.006, 0.006)
        yaw = rng.uniform(-12.0, 12.0)
        xyz = (x, y, z)
        set_bag_pose(prim, xyz, yaw)
        scene_bags.append({
            "name": prim.GetName(),
            "prim_path": str(prim.GetPath()),
            "xyz_local_m": list(xyz),
            "yaw_deg": yaw,
        })
    return scene_bags


def generate_dataset(camera, render_product: str) -> None:
    """Generate randomized RGB, depth, and perfect instance annotations."""
    if args.dataset_samples <= 0:
        raise ValueError("dataset-samples must be positive")
    output = select_dataset_output(Path(args.dataset_output))

    bag_prims = find_bag_prims()
    if not bag_prims:
        raise RuntimeError("No chemical_bag_* prims found after URDF import")
    if not 1 <= args.min_bags <= args.max_bags <= len(bag_prims):
        raise ValueError(
            f"Bag range must satisfy 1 <= min <= max <= {len(bag_prims)}"
        )
    hide_robot_for_dataset()
    for prim in bag_prims:
        add_labels(prim, labels=["bag"], taxonomy="class")
        add_labels(
            prim, labels=[prim.GetName()], taxonomy="instance_name"
        )

    temporary = output / ".replicator"
    temporary.mkdir()
    annotators = {
        "rgb": rep.AnnotatorRegistry.get_annotator("rgb"),
        "depth": rep.AnnotatorRegistry.get_annotator(
            "distance_to_image_plane"
        ),
        "instance": rep.AnnotatorRegistry.get_annotator(
            "semantic_segmentation", init_params={"colorize": False}
        ),
        "camera": rep.AnnotatorRegistry.get_annotator("camera_params"),
    }
    for annotator in annotators.values():
        annotator.attach(render_product)

    rng = random.Random(args.dataset_seed)
    scenes = []
    for sample_index in range(args.dataset_samples):
        bag_count = rng.randint(args.min_bags, args.max_bags)
        scene_bags = randomize_bags(bag_prims, bag_count, rng)
        simulation_app.update()
        # RTX semantic/instance state trails a USD visibility change by one
        # capture. Discard a settling capture before reading the annotators.
        rep.orchestrator.step(
            rt_subframes=4, delta_time=1.0 / CAMERA_RATE_HZ
        )
        simulation_app.update()
        rep.orchestrator.step(
            rt_subframes=4, delta_time=1.0 / CAMERA_RATE_HZ
        )
        _write_annotator_frame(
            temporary, f"{sample_index:04d}", annotators
        )
        scenes.append({
            "sample_index": sample_index,
            "bag_count": bag_count,
            "bags": scene_bags,
        })
        if sample_index == 0 or (sample_index + 1) % 100 == 0:
            print(
                f"Rendered {sample_index + 1}/{args.dataset_samples} "
                f"dataset scenes",
                flush=True,
            )
    for annotator in annotators.values():
        annotator.detach()
    convert_replicator_output(temporary, output, scenes)
    (output / "generation.json").write_text(
        json.dumps({
            "sample_count": args.dataset_samples,
            "seed": args.dataset_seed,
            "min_bags": args.min_bags,
            "max_bags": args.max_bags,
            "resolution": list(camera.get_resolution()),
            "depth_encoding": "16UC1",
            "depth_unit": "millimetres",
            "pointcloud_unit": "metres",
        }, indent=2) + "\n",
        encoding="utf-8",
    )


def initialize_writer(writer_name: str, topic: str, render_product: str):
    """Attach an image-derived ROS writer to the camera render product."""
    writer = rep.writers.get(writer_name)
    writer.initialize(
        frameId=FRAME_ID,
        nodeNamespace=NAMESPACE,
        queueSize=1,
        topicName=topic,
    )
    writer.attach([render_product])
    return writer


def publish_camera_info(render_product: str) -> None:
    """Publish pinhole calibration corresponding to the rendered camera."""
    # This module becomes available only after enabling the ROS 2 extension.
    from isaacsim.ros2.core import read_camera_info

    camera_info, _ = read_camera_info(render_product_path=render_product)
    writer = rep.writers.get("ROS2PublishCameraInfo")
    writer.initialize(
        frameId=FRAME_ID,
        nodeNamespace=NAMESPACE,
        queueSize=1,
        topicName=INFO_TOPIC,
        width=camera_info.width,
        height=camera_info.height,
        projectionType=camera_info.distortion_model,
        k=camera_info.k.reshape([1, 9]),
        r=camera_info.r.reshape([1, 9]),
        p=camera_info.p.reshape([1, 12]),
        physicalDistortionModel=camera_info.distortion_model,
        physicalDistortionCoefficients=camera_info.d,
    )
    writer.attach([render_product])


def main() -> None:
    """Run Isaac until the application or parent ROS launch exits."""
    if not args.dataset_samples:
        app_utils.enable_extension("isaacsim.ros2.bridge")
        simulation_app.update()

    usd_path = import_robot()
    omni.usd.get_context().open_stage(usd_path, None)
    while omni.usd.get_context().get_stage_loading_status()[2] > 0:
        simulation_app.update()
    stage_utils.set_stage_units(meters_per_unit=1.0)
    create_environment_light()

    # Camera uses the world/ROS body-axis convention. Pitching +90 degrees
    # aligns its optical +Z axis with cell -Z, directly above the pallet.
    camera = Camera(
        prim_path=CAMERA_PATH,
        position=np.array([1.4, 0.0, 2.0]),
        orientation=transform_utils.euler_angles_to_quaternion(
            np.array([0.0, 90.0, 0.0]), degrees=True
        ).numpy(),
        frequency=CAMERA_RATE_HZ,
        resolution=(640, 480),
    )
    camera.initialize()
    camera.set_clipping_range(0.1, 3.0)
    camera.set_horizontal_aperture(20.955)
    camera.set_focal_length(13.656)
    simulation_app.update()

    render_product = camera._render_product_path
    if args.dataset_samples:
        try:
            generate_dataset(camera, render_product)
        except BaseException:
            traceback.print_exc()
            raise
        finally:
            simulation_app.close()
        return

    rgb_rv = omni.syntheticdata.SyntheticData.convert_sensor_type_to_rendervar(
        sd.SensorType.Rgb.name
    )
    initialize_writer(rgb_rv + "ROS2PublishImage", RGB_TOPIC, render_product)
    depth_rv = omni.syntheticdata.SyntheticData.convert_sensor_type_to_rendervar(
        sd.SensorType.DistanceToImagePlane.name
    )
    initialize_writer(depth_rv + "ROS2PublishImage", DEPTH_TOPIC, render_product)
    initialize_writer(depth_rv + "ROS2PublishPointCloud", POINTS_TOPIC, render_product)
    publish_camera_info(render_product)
    camera_step = SIMULATION_RATE_HZ // CAMERA_RATE_HZ
    rgb_gate = omni.syntheticdata.SyntheticData._get_node_path(
        rgb_rv + "IsaacSimulationGate", render_product
    )
    depth_gate = omni.syntheticdata.SyntheticData._get_node_path(
        depth_rv + "IsaacSimulationGate", render_product
    )
    info_gate = omni.syntheticdata.SyntheticData._get_node_path(
        "PostProcessDispatchIsaacSimulationGate", render_product
    )
    og.Controller.attribute(rgb_gate + ".inputs:step").set(camera_step)
    og.Controller.attribute(depth_gate + ".inputs:step").set(camera_step)
    og.Controller.attribute(info_gate + ".inputs:step").set(camera_step)
    create_clock_graph()

    SimulationManager.setup_simulation(
        dt=1.0 / SIMULATION_RATE_HZ, device="cpu"
    )
    app_utils.play()
    simulation_app.update()
    steps = 0
    while simulation_app.is_running():
        simulation_app.update()
        steps += 1
        if args.test_steps and steps >= args.test_steps:
            break
    app_utils.stop()
    simulation_app.close()


if __name__ == "__main__":
    main()
