#!/usr/bin/env python3
"""Generate the low-poly visual mesh for a filled industrial sack."""

from math import cos, pi, sin
from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / "meshes" / "chemical_bag.obj"

# A common 20--25 kg industrial sack is roughly 600 x 400 x 160 mm.
LENGTH = 0.60
WIDTH = 0.40
HEIGHT = 0.16
RINGS = 31
POINTS_PER_RING = 24
CAP_LENGTH = 0.075


def ring_vertex(ring: int, point: int) -> tuple[float, float, float]:
    """Return an asymmetric, pillow-like sack surface point."""
    # The actual end points are separate pole vertices. These intermediate
    # rings shrink progressively so the sack closes as a curved surface rather
    # than as a flat circular cap.
    u = (ring + 1) / (RINGS + 1)
    cap_fraction = CAP_LENGTH / LENGTH

    # Elliptical end caps have a zero slope at the tip and blend tangentially
    # into the full bag body. This avoids both flat end disks and conical tips.
    if u < cap_fraction:
        angle = 0.5 * pi * u / cap_fraction
        x = -0.5 * LENGTH + CAP_LENGTH * (1.0 - cos(angle))
        end_taper = sin(angle)
    elif u > 1.0 - cap_fraction:
        angle = 0.5 * pi * (1.0 - u) / cap_fraction
        x = 0.5 * LENGTH - CAP_LENGTH * (1.0 - cos(angle))
        end_taper = sin(angle)
    else:
        body_u = (u - cap_fraction) / (1.0 - 2.0 * cap_fraction)
        x = -0.5 * LENGTH + CAP_LENGTH + body_u * (LENGTH - 2.0 * CAP_LENGTH)
        end_taper = 1.0

    perimeter_angle = 2.0 * pi * point / POINTS_PER_RING
    y = 0.5 * WIDTH * end_taper * cos(perimeter_angle)
    z = 0.5 * HEIGHT * end_taper * sin(perimeter_angle)

    # Small deterministic distortions stop the visual from looking manufactured.
    y *= 1.0 + 0.025 * sin(3.0 * perimeter_angle + 5.0 * u)
    z *= 1.0 + 0.045 * sin(2.0 * perimeter_angle - 4.0 * u)
    z += 0.009 * sin(pi * u) * cos(perimeter_angle) ** 2
    return x, y, z


def generate() -> str:
    lines = [
        "# Filled 25 kg chemical sack, generated by generate_chemical_bag_mesh.py",
        "o chemical_bag",
    ]
    vertices = [
        ring_vertex(ring, point)
        for ring in range(RINGS)
        for point in range(POINTS_PER_RING)
    ]
    # Single vertices at the sealed ends produce rounded, non-planar closures.
    vertices.extend([(-LENGTH / 2, 0.0, -0.004), (LENGTH / 2, 0.0, 0.003)])
    lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in vertices)
    lines.append("s 1")

    for ring in range(RINGS - 1):
        for point in range(POINTS_PER_RING):
            nxt = (point + 1) % POINTS_PER_RING
            a = ring * POINTS_PER_RING + point + 1
            b = ring * POINTS_PER_RING + nxt + 1
            c = (ring + 1) * POINTS_PER_RING + nxt + 1
            d = (ring + 1) * POINTS_PER_RING + point + 1
            lines.append(f"f {a} {b} {c} {d}")

    left_tip = RINGS * POINTS_PER_RING + 1
    right_tip = left_tip + 1
    for point in range(POINTS_PER_RING):
        nxt = (point + 1) % POINTS_PER_RING
        lines.append(f"f {left_tip} {nxt + 1} {point + 1}")
        last = (RINGS - 1) * POINTS_PER_RING
        lines.append(f"f {right_tip} {last + point + 1} {last + nxt + 1}")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")
