joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.490658503988659
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.054326190990077
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.316125578789226
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.504915783575617
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.504915783575617
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.995574287564276
